import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";
import {
  History,
  ArrowRight,
  CheckCircle2,
  Clock,
  AlertCircle,
  Search,
  RefreshCw,
  BarChart3,
} from "lucide-react";
import { historyApi } from "@/services/api";

function cn(...classes: ClassValue[]) {
  return twMerge(clsx(classes));
}

function StatusBadge({ status }: { status: string }) {
  const isComplete = status === "completed";
  const isError = status === "failed" || status === "error";

  return (
    <span
      className={cn(
        "badge",
        isComplete && "badge-success",
        isError && "badge-error",
        !isComplete && !isError && "badge-warning"
      )}
    >
      {isComplete && <CheckCircle2 className="w-3 h-3" />}
      {isError && <AlertCircle className="w-3 h-3" />}
      {!isComplete && !isError && <Clock className="w-3 h-3" />}
      {status}
    </span>
  );
}

export default function HistoryPage() {
  const [search, setSearch] = useState("");

  const { data: history, isLoading, isFetching, refetch } = useQuery({
    queryKey: ["history"],
    queryFn: historyApi.list,
  });

  const filtered = history?.filter(
    (h) =>
      h.request.toLowerCase().includes(search.toLowerCase()) ||
      h.run_id.toLowerCase().includes(search.toLowerCase())
  ) ?? [];

  const stats = {
    total: history?.length ?? 0,
    completed: history?.filter((h) => h.status === "completed").length ?? 0,
    failed: history?.filter((h) => h.status === "failed").length ?? 0,
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <div className="animate-slide-up">
        <h1 className="text-2xl font-bold text-foreground tracking-tight">
          Analysis History
        </h1>
        <p className="text-muted-foreground text-sm mt-1">
          All portfolio analyses generated by the multi-agent pipeline
        </p>
      </div>

      {/* Stats */}
      <div
        className="grid grid-cols-3 gap-4 animate-slide-up"
        style={{ animationDelay: "100ms", animationFillMode: "both" }}
      >
        {[
          { label: "Total", value: stats.total, color: "bg-primary/10 text-primary" },
          { label: "Completed", value: stats.completed, color: "bg-success/10 text-success" },
          { label: "Failed", value: stats.failed, color: "bg-danger/10 text-danger" },
        ].map((s) => (
          <div key={s.label} className="card p-5 flex items-center gap-4">
            <div className={cn("w-10 h-10 rounded-xl flex items-center justify-center", s.color)}>
              <BarChart3 className="w-5 h-5" />
            </div>
            <div>
              <p className="stat-value">{s.value}</p>
              <p className="stat-label">{s.label}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Controls */}
      <div
        className="card p-4 flex items-center gap-4 animate-slide-up"
        style={{ animationDelay: "150ms", animationFillMode: "both" }}
      >
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <input
            type="text"
            className="input pl-10"
            placeholder="Search by request or ID..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <button onClick={() => refetch()} disabled={isFetching} className="btn-ghost" title="Refresh">
          <RefreshCw className={cn("w-4 h-4", isFetching && "animate-spin")} />
        </button>
      </div>

      {/* List */}
      <div className="animate-slide-up" style={{ animationDelay: "200ms", animationFillMode: "both" }}>
        {isLoading ? (
          <div className="card p-12 flex flex-col items-center justify-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
              <History className="w-5 h-5 text-primary animate-pulse" />
            </div>
            <p className="text-muted-foreground font-medium">Loading history...</p>
          </div>
        ) : filtered.length === 0 ? (
          <div className="card p-12 flex flex-col items-center justify-center gap-3">
            <div className="w-14 h-14 rounded-2xl bg-muted flex items-center justify-center">
              <History className="w-7 h-7 text-muted-foreground" />
            </div>
            <p className="text-foreground font-semibold">No analyses found</p>
            <p className="text-muted-foreground text-sm">
              {search ? "Try a different search term" : "Run your first portfolio analysis to see it here"}
            </p>
            {!search && (
              <Link to="/analysis" className="btn-primary mt-2 text-sm">
                Start Analysis
              </Link>
            )}
          </div>
        ) : (
          <div className="card divide-y divide-border">
            {filtered.map((item, i) => (
              <Link
                key={item.run_id}
                to={`/report/${item.run_id}`}
                className="flex items-center gap-4 px-5 py-4 hover:bg-muted/30 transition-all duration-200 group"
                style={{ animationDelay: `${i * 50}ms`, animationFillMode: "both" }}
              >
                <div
                  className={cn(
                    "w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0",
                    item.status === "completed" && "bg-success/10",
                    (item.status === "failed" || item.status === "error") && "bg-danger/10",
                    item.status === "pending" && "bg-muted"
                  )}
                >
                  {item.status === "completed" && (
                    <CheckCircle2 className="w-5 h-5 text-success" />
                  )}
                  {(item.status === "failed" || item.status === "error") && (
                    <AlertCircle className="w-5 h-5 text-danger" />
                  )}
                  {item.status === "pending" && <Clock className="w-5 h-5 text-muted-foreground" />}
                </div>

                <div className="flex-1 min-w-0">
                  <p className="text-sm font-semibold text-foreground truncate group-hover:text-primary transition-colors">
                    {item.request}
                  </p>
                  <div className="flex items-center gap-3 mt-1">
                    <span className="text-xs text-muted-foreground font-mono">{item.run_id}</span>
                    <span className="text-muted-foreground/30">&bull;</span>
                    <span className="text-xs text-muted-foreground">
                      {new Date(item.timestamp).toLocaleString("en-US", {
                      timeZone: "Asia/Ho_Chi_Minh",
                      year: "numeric",
                      month: "2-digit",
                      day: "2-digit",
                      hour: "2-digit",
                      minute: "2-digit",
                    })}
                    </span>
                  </div>
                </div>

                <div className="flex items-center gap-3 flex-shrink-0">
                  <StatusBadge status={item.status} />
                  <ArrowRight className="w-4 h-4 text-muted-foreground/40 group-hover:text-primary transition-colors" />
                </div>
              </Link>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
