import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { clsx } from 'clsx'
import {
  History,
  ArrowRight,
  CheckCircle2,
  Clock,
  AlertCircle,
  Search,
  RefreshCw,
  BarChart3,
} from 'lucide-react'
import { historyApi } from '../services/api'

function StatusBadge({ status }: { status: string }) {
  const isComplete = status === 'completed'
  const isError = status === 'failed' || status === 'error'

  return (
    <span className={clsx(
      'badge',
      isComplete && 'badge-success',
      isError && 'badge-error',
      !isComplete && !isError && 'badge-warning',
    )}>
      {isComplete && <CheckCircle2 className="w-3 h-3" />}
      {isError && <AlertCircle className="w-3 h-3" />}
      {!isComplete && !isError && <Clock className="w-3 h-3" />}
      {status}
    </span>
  )
}

export default function HistoryPage() {
  const [search, setSearch] = useState('')

  const { data: history, isLoading, isFetching, refetch } = useQuery({
    queryKey: ['history'],
    queryFn: historyApi.list,
  })

  const filtered = history?.filter((h) =>
    h.request.toLowerCase().includes(search.toLowerCase()) ||
    h.run_id.toLowerCase().includes(search.toLowerCase()),
  ) ?? []

  const stats = {
    total: history?.length ?? 0,
    completed: history?.filter((h) => h.status === 'completed').length ?? 0,
    failed: history?.filter((h) => h.status === 'failed').length ?? 0,
  }

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      {/* Header */}
      <div className="animate-fade-in">
        <h1 className="text-2xl font-bold text-surface-900 tracking-tight">Analysis History</h1>
        <p className="text-surface-500 mt-1">
          All portfolio analyses generated by the multi-agent pipeline
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-4 animate-slide-up" style={{ animationDelay: '100ms', animationFillMode: 'both' }}>
        {[
          { label: 'Total', value: stats.total, color: 'bg-navy-500' },
          { label: 'Completed', value: stats.completed, color: 'bg-emerald-500' },
          { label: 'Failed', value: stats.failed, color: 'bg-red-500' },
        ].map((s) => (
          <div key={s.label} className="card p-5 flex items-center gap-4">
            <div className={clsx('w-10 h-10 rounded-xl flex items-center justify-center', s.color)}>
              <BarChart3 className="w-5 h-5 text-white" />
            </div>
            <div>
              <p className="stat-value">{s.value}</p>
              <p className="stat-label">{s.label}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Controls */}
      <div className="card p-4 flex items-center gap-4 animate-slide-up" style={{ animationDelay: '150ms', animationFillMode: 'both' }}>
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-surface-400" />
          <input
            type="text"
            className="input pl-10"
            placeholder="Search by request or ID..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <button
          onClick={() => refetch()}
          disabled={isFetching}
          className="btn-ghost"
          title="Refresh"
        >
          <RefreshCw className={clsx('w-4 h-4', isFetching && 'animate-spin')} />
        </button>
      </div>

      {/* List */}
      <div className="animate-slide-up" style={{ animationDelay: '200ms', animationFillMode: 'both' }}>
        {isLoading ? (
          <div className="card p-12 flex flex-col items-center justify-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-navy-50 flex items-center justify-center">
              <History className="w-5 h-5 text-navy-500 animate-pulse" />
            </div>
            <p className="text-surface-500 font-medium">Loading history...</p>
          </div>
        ) : filtered.length === 0 ? (
          <div className="card p-12 flex flex-col items-center justify-center gap-3">
            <div className="w-14 h-14 rounded-2xl bg-surface-100 flex items-center justify-center">
              <History className="w-7 h-7 text-surface-400" />
            </div>
            <p className="text-surface-600 font-semibold">No analyses found</p>
            <p className="text-surface-400 text-sm">
              {search ? 'Try a different search term' : 'Run your first portfolio analysis to see it here'}
            </p>
            {!search && (
              <Link to="/analysis" className="btn-primary mt-2 text-sm">
                Start Analysis
              </Link>
            )}
          </div>
        ) : (
          <div className="card divide-y divide-surface-100">
            {filtered.map((item, i) => (
              <Link
                key={item.run_id}
                to={`/report/${item.run_id}`}
                className="flex items-center gap-4 px-5 py-4 hover:bg-surface-50 transition-all duration-200 group"
                style={{ animationDelay: `${i * 50}ms`, animationFillMode: 'both' }}
              >
                <div className={clsx(
                  'w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0',
                  item.status === 'completed' ? 'bg-emerald-50' :
                  item.status === 'failed' ? 'bg-red-50' : 'bg-amber-50',
                )}>
                  {item.status === 'completed' ? (
                    <CheckCircle2 className="w-5 h-5 text-emerald-600" />
                  ) : item.status === 'failed' ? (
                    <AlertCircle className="w-5 h-5 text-red-600" />
                  ) : (
                    <Clock className="w-5 h-5 text-amber-600" />
                  )}
                </div>

                <div className="flex-1 min-w-0">
                  <p className="text-sm font-semibold text-surface-800 truncate group-hover:text-navy-700 transition-colors">
                    {item.request}
                  </p>
                  <div className="flex items-center gap-3 mt-1">
                    <span className="text-xs text-surface-400 font-mono">{item.run_id}</span>
                    <span className="text-xs text-surface-300">&bull;</span>
                    <span className="text-xs text-surface-400">
                      {new Date(item.timestamp).toLocaleString()}
                    </span>
                    <span className="text-xs text-surface-300">&bull;</span>
                    <span className="text-xs text-surface-400 font-medium uppercase">
                      {item.lang}
                    </span>
                  </div>
                </div>

                <div className="flex items-center gap-3 flex-shrink-0">
                  <StatusBadge status={item.status} />
                  <ArrowRight className="w-4 h-4 text-surface-300 group-hover:text-navy-500 transition-colors" />
                </div>
              </Link>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
