spring.application.name=notification-service
server.port=8084

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:notification-group}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.listener.missing-topics-fatal=false

app.kafka.notification-topic=${APP_KAFKA_NOTIFICATION_TOPIC:notificationTopic}

spring.data.mongodb.uri=${NOTIFICATION_MONGO_URI:mongodb://product_user:product_password@localhost:27017/notification_db?authSource=admin}

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
