apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: staging

replicas:
  - name: api-gateway
    count: 3
  - name: user-service
    count: 3
  - name: market-data-service
    count: 3
  - name: portfolio-service
    count: 3
  - name: notification-service
    count: 2
  - name: multi-agents-service
    count: 3
  - name: eureka-server
    count: 1
  - name: frontend
    count: 3

images:
  - name: registry.gitlab.com/callmesen-group/ccnlthd/api-gateway
    newTag: staging-latest
  - name: registry.gitlab.com/callmesen-group/ccnlthd/user-service
    newTag: staging-latest
  - name: registry.gitlab.com/callmesen-group/ccnlthd/market-data-service
    newTag: staging-latest
  - name: registry.gitlab.com/callmesen-group/ccnlthd/portfolio-service
    newTag: staging-latest
  - name: registry.gitlab.com/callmesen-group/ccnlthd/notification-service
    newTag: staging-latest
  - name: registry.gitlab.com/callmesen-group/ccnlthd/multi-agents-service
    newTag: staging-latest
  - name: registry.gitlab.com/callmesen-group/ccnlthd/eureka-server
    newTag: staging-latest
  - name: registry.gitlab.com/callmesen-group/ccnlthd/frontend
    newTag: staging-latest
