apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: investadvisor
  labels:
    app: notification-service
    app.kubernetes.io/name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: registry.gitlab.com/callmesen-group/ccnlthd/notification-service:latest
          ports:
            - containerPort: 8084
              name: http
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PASSWORD
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: EUREKA_HOST
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: KAFKA_BROKERS
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MAIL_PORT
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-secrets
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-secrets
                  key: MAIL_PASSWORD
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 3
