apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-service
  namespace: investadvisor
  labels:
    app: portfolio-service
    app.kubernetes.io/name: portfolio-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-service
  template:
    metadata:
      labels:
        app: portfolio-service
    spec:
      containers:
        - name: portfolio-service
          image: docker.io/callmesen/investadvisor-portfolio-service:latest
          ports:
            - containerPort: 8083
              name: http
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PASSWORD
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: EUREKA_HOST
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: KAFKA_BROKERS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
            - name: MARKET_DATA_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MARKET_DATA_HOST
            - name: MARKET_DATA_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MARKET_DATA_PORT
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 3
