apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-vault-dev-application.yaml
  - argocd-vault-dev-bootstrap-application.yaml
  - argocd-external-secrets-application.yaml
  - argocd-application.yaml
