apiVersion: v1
kind: Service
metadata:
  name: multi-agents-service
  namespace: investadvisor
  labels:
    app: multi-agents-service
spec:
  selector:
    app: multi-agents-service
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30500
      name: http
      protocol: TCP
  type: NodePort
