apiVersion: v1
kind: Service
metadata:
  name: zookeeper-nodeport
  namespace: investadvisor
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
      nodePort: 30800
      name: zookeeper
      protocol: TCP
  type: NodePort
