apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: investadvisor
  labels:
    app: portfolio-service
spec:
  selector:
    app: portfolio-service
  ports:
    - port: 8083
      targetPort: 8083
      name: http
      protocol: TCP
  type: ClusterIP
