apiVersion: v1
kind: Service
metadata:
  name: postgres-ma-nodeport
  namespace: investadvisor
  labels:
    app: postgres-ma
spec:
  selector:
    app: postgres-ma
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 31543
      name: postgres
      protocol: TCP
  type: NodePort
