"""
Markdown report formatter for portfolio generation output.
"""
import logging
from typing import Dict


_REPORT_HEADERS_EN = {
    "title": "# Financial Portfolio Report",
    "execution_error": "## Execution Error",
    "user_profile_summary": "## User Profile Summary",
    "goal": "Goal",
    "risk_tolerance": "Risk Tolerance",
    "time_horizon": "Time Horizon",
    "initial_capital": "Initial Capital",
    "preferences": "Preferences",
    "market_news": "## Recent Market News Context",
    "proposed_portfolio": "## Proposed Portfolio Allocation",
    "asset_col": "Asset",
    "weight_col": "Weight",
    "no_portfolio": "No valid portfolio allocation was proposed.",
    "portfolio_metrics": "## Portfolio Performance Metrics",
    "included_assets": "Included Assets",
    "period_days": "Calculation Period Days",
    "metric_col": "Metric",
    "value_col": "Value",
    "total_return": "Total Return",
    "annualized_return": "Annualized Return",
    "volatility": "Annualized Volatility",
    "sharpe": "Sharpe Ratio",
    "max_drawdown": "Max Drawdown",
    "capm_expected": "Expected Return (CAPM)",
    "momentum": "Momentum Outlook (SMA)",
    "capm_note": "CAPM Expected Return: Rf={rf:.1%}, E(Rm)={em:.1%}.",
    "capm_coverage": "Portfolio CAPM calculation covers {pct:.1%} of portfolio weight.",
    "metrics_error": "Metrics Calculation Error",
    "no_metrics": "Portfolio metrics not calculated.",
    "unavailable": "Portfolio metrics are unavailable.",
    "individual_metrics": "## Individual Asset Metrics",
    "ann_return": "Ann. Return",
    "asset_volatility": "Volatility",
    "beta": "Beta",
    "sma50": "SMA 50",
    "sma200": "SMA 200",
    "validation": "## Validation Status",
    "status": "Status",
    "issues": "Issues Found",
    "validation_failed": "Validation did not run or failed.",
    "commentary": "## LLM Commentary & Reasoning",
    "disclaimer": "**Disclaimer:** This report is generated by an AI system for informational purposes only. It does not constitute financial advice. Consult with a qualified financial advisor before making investment decisions.",
    "no_commentary": "No commentary generated.",
}

_REPORT_HEADERS_VI = {
    "title": "# Báo Cáo Danh Mục Đầu Tư",
    "execution_error": "## Lỗi Thực Thi",
    "user_profile_summary": "## Tóm Tắt Hồ Sơ Người Dùng",
    "goal": "Mục tiêu",
    "risk_tolerance": "Mức chấp nhận rủi ro",
    "time_horizon": "Thời hạn đầu tư",
    "initial_capital": "Vốn ban đầu",
    "preferences": "Sở thích",
    "market_news": "## Bối Cảnh Tin Tức Thị Trường Gần Đây",
    "proposed_portfolio": "## Phân Bổ Danh Mục Đề Xuất",
    "asset_col": "Tài sản",
    "weight_col": "Tỷ trọng",
    "no_portfolio": "Không có phân bổ danh mục hợp lệ nào được đề xuất.",
    "portfolio_metrics": "## Chỉ Số Hiệu Suất Danh Mục",
    "included_assets": "Tài sản được bao gồm",
    "period_days": "Số ngày tính toán",
    "metric_col": "Chỉ số",
    "value_col": "Giá trị",
    "total_return": "Lợi suất tổng",
    "annualized_return": "Lợi suất hàng năm",
    "volatility": "Biến động hàng năm",
    "sharpe": "Tỷ số Sharpe",
    "max_drawdown": "Đà giảm tối đa",
    "capm_expected": "Lợi suất kỳ vọng (CAPM)",
    "momentum": "Triển vọng động lượng (SMA)",
    "capm_note": "Lợi suất kỳ vọng CAPM: Rf={rf:.1%}, E(Rm)={em:.1%}.",
    "capm_coverage": "Tính toán CAPM của danh mục bao gồm {pct:.1%} trọng lượng danh mục.",
    "metrics_error": "Lỗi tính toán chỉ số",
    "no_metrics": "Chỉ số danh mục chưa được tính toán.",
    "unavailable": "Chỉ số danh mục không khả dụng.",
    "individual_metrics": "## Chỉ Số Tài Sản Cá Nhân",
    "ann_return": "LS hàng năm",
    "asset_volatility": "Biến động",
    "beta": "Beta",
    "sma50": "SMA 50",
    "sma200": "SMA 200",
    "validation": "## Trạng Thái Xác Thực",
    "status": "Trạng thái",
    "issues": "Vấn đề được tìm thấy",
    "validation_failed": "Xác thực không chạy hoặc thất bại.",
    "commentary": "## Bình Luận & Lý Do từ LLM",
    "disclaimer": "**Tuyên bố miễn trừ trách nhiệm:** Báo cáo này được tạo bởi hệ thống AI chỉ nhằm mục đích thông tin. Nó không cấu thành lời khuyên tài chính. Hãy tham khảo ý kiến cố vấn tài chính có trình độ trước khi đưa ra quyết định đầu tư.",
    "no_commentary": "Không có bình luận được tạo.",
}


def structure_output_report(state: Dict) -> str:
    """Formats the final results into a clear Markdown report using tables."""
    logging.info("Structuring Output Report")

    lang = state.get("lang", "en")
    T = _REPORT_HEADERS_VI if lang == "vi" else _REPORT_HEADERS_EN
    rf_rate = 0.045
    exp_market_return = 0.09

    user_profile = state.get("user_profile", {})
    proposed_portfolio = state.get("proposed_portfolio", {})
    metrics = state.get("metrics", {})
    validation = state.get("validation_result", {})
    commentary = state.get("llm_commentary") or T["no_commentary"]
    news = state.get("market_news", None)
    error_msg = state.get("error_message", None)

    report = T["title"] + "\n\n"

    if error_msg:
        report += T["execution_error"] + f"\n{error_msg}\n\n"

    report += T["user_profile_summary"] + "\n"
    report += f"- **{T['goal']}:** {user_profile.get('goal', 'N/A')}\n"
    report += f"- **{T['risk_tolerance']}:** {user_profile.get('risk_tolerance', 'N/A')}\n"
    report += f"- **{T['time_horizon']}:** {user_profile.get('time_horizon', 'N/A')}\n"
    capital = user_profile.get("initial_capital")
    if capital:
        report += f"- **{T['initial_capital']}:** ${capital:,.2f}\n"
    prefs = user_profile.get("specific_preferences") or user_profile.get("preferences")
    if prefs:
        report += f"- **{T['preferences']}:** {prefs}\n"
    report += "\n"

    if news:
        report += T["market_news"] + f"\n{news}\n\n"

    report += T["proposed_portfolio"] + "\n"
    if isinstance(proposed_portfolio, dict) and proposed_portfolio:
        report += f"| {T['asset_col']} | {T['weight_col']} |\n|-------|--------|\n"
        for ticker, weight in proposed_portfolio.items():
            report += f"| {ticker.upper()} | {weight:.2%} |\n"
    else:
        report += f"- {T['no_portfolio']}\n"
    report += "\n"

    report += T["portfolio_metrics"] + "\n"
    portfolio_metrics = metrics.get("portfolio", {}) if isinstance(metrics, dict) else {}
    if isinstance(portfolio_metrics, dict) and "error" not in portfolio_metrics and proposed_portfolio:
        included_assets_str = ", ".join(portfolio_metrics.get("included_assets", list(proposed_portfolio.keys())))
        report += f"- **{T['included_assets']}:** {included_assets_str}\n"
        report += f"- **{T['period_days']}:** {portfolio_metrics.get('period_days', 'N/A')}\n"
        report += f"| {T['metric_col']} | {T['value_col']} |\n|--------------------------------|------------|\n"

        def fmt(value, spec):
            if isinstance(value, (int, float)):
                try:
                    return format(value, spec)
                except (ValueError, TypeError):
                    return str(value)
            return str(value) if value is not None else "N/A"

        report += f"| {T['total_return']} | {fmt(portfolio_metrics.get('total_return'), '.2%')} |\n"
        report += f"| {T['annualized_return']} | {fmt(portfolio_metrics.get('annualized_return'), '.2%')} |\n"
        report += f"| {T['volatility']} | {fmt(portfolio_metrics.get('annualized_volatility'), '.2%')} |\n"
        report += f"| {T['sharpe']} | {fmt(portfolio_metrics.get('sharpe_ratio'), '.2f')} |\n"
        report += f"| {T['max_drawdown']} | {fmt(portfolio_metrics.get('max_drawdown'), '.2%')} |\n"
        exp_ret_capm = portfolio_metrics.get("expected_return_capm")
        report += f"| {T['capm_expected']} | {fmt(exp_ret_capm, '.2%')} |\n"
        momentum = portfolio_metrics.get("portfolio_momentum_outlook", "N/A")
        report += f"| {T['momentum']} | {momentum} |\n"
        report += f"*{T['capm_note'].format(rf=rf_rate, em=exp_market_return)}*\n"
        capm_coverage = portfolio_metrics.get("capm_calculation_weight_coverage")
        if capm_coverage is not None:
            report += f"*{T['capm_coverage'].format(pct=capm_coverage)}*\n"
    elif isinstance(portfolio_metrics, dict) and "error" in portfolio_metrics:
        report += f"- **{T['metrics_error']}:** {portfolio_metrics['error']}\n"
    elif not proposed_portfolio:
        report += f"- {T['no_metrics']}\n"
    else:
        report += f"- {T['unavailable']}\n"
    report += "\n"

    if isinstance(metrics, dict) and proposed_portfolio:
        report += T["individual_metrics"] + "\n"
        report += f"*{T['capm_note'].format(rf=rf_rate, em=exp_market_return)}*\n"
        report += f"| {T['asset_col']} | {T['ann_return']} | {T['asset_volatility']} | {T['sharpe']} | {T['max_drawdown']} | {T['capm_expected']} | {T['beta']} | {T['sma50']} | {T['sma200']} |\n"
        report += "|-------|-------------|------------|--------|--------------|--------------------|------|--------|---------|\n"
        for ticker in proposed_portfolio.keys():
            asset_metrics = metrics.get(ticker.upper())
            if isinstance(asset_metrics, dict):
                report += f"| **{ticker.upper()}** | "
                report += f"{fmt(asset_metrics.get('annualized_return'), '.2%')} | "
                report += f"{fmt(asset_metrics.get('annualized_volatility'), '.2%')} | "
                report += f"{fmt(asset_metrics.get('sharpe_ratio'), '.2f')} | "
                report += f"{fmt(asset_metrics.get('max_drawdown'), '.2%')} | "
                report += f"{fmt(asset_metrics.get('expected_return_capm'), '.2%')} | "
                report += f"{fmt(asset_metrics.get('beta'), '.2f')} | "
                report += f"{fmt(asset_metrics.get('sma_50'), '.2f')} | "
                report += f"{fmt(asset_metrics.get('sma_200'), '.2f')} |\n"
        report += "\n"

    report += T["validation"] + "\n"
    if isinstance(validation, dict):
        report += f"- **{T['status']}:** {validation.get('status', 'N/A').upper()}\n"
        if validation.get("errors"):
            report += f"- **{T['issues']}:**\n"
            for err in validation["errors"]:
                report += f"  - {err}\n"
    else:
        report += f"- {T['validation_failed']}\n"
    report += "\n"

    report += T["commentary"] + "\n"
    report += f"{commentary}\n\n"
    report += "---\n"
    report += T["disclaimer"] + "\n"
    logging.info("Report Structuring Complete")
    return report
