name: microservices-demo

services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:16
    container_name: inventory-postgres
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user -d inventory_db"]
      interval: 10s
      timeout: 5s
      retries: 10


  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
      MYSQL_USER: order_user
      MYSQL_PASSWORD: order_password
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: product_user
      MONGO_INITDB_ROOT_PASSWORD: product_password
      MONGO_INITDB_DATABASE: product_db
    volumes:
      - mongo-data:/data/db

  eureka-server:
    build:
      context: ./eureka_server
    ports:
      - "8761:8761"

  inventory-service:
    build:
      context: ./inventory_service
    depends_on:
      - eureka-server
      - postgres
      - kafka
      - zipkin
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      INVENTORY_DB_URL: jdbc:postgresql://postgres:5432/inventory_db
      INVENTORY_DB_USERNAME: inventory_user
      INVENTORY_DB_PASSWORD: inventory_password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8081"

  order-service:
    build:
      context: ./order_service
    depends_on:
      eureka-server:
        condition: service_started
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      inventory-service:
        condition: service_started
      zipkin:
        condition: service_started
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      ORDER_DB_URL: jdbc:mysql://mysql:3306/order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      ORDER_DB_USERNAME: root
      ORDER_DB_PASSWORD: root
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      INVENTORY_SERVICE_URL: http://inventory-service:8081
    ports:
      - "8082:8082"

  product-service:
    build:
      context: ./product_service
    depends_on:
      - eureka-server
      - mongodb
      - zipkin
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      PRODUCT_MONGO_URI: mongodb://product_user:product_password@mongodb:27017/product_db?authSource=admin
    ports:
      - "8083:8083"

volumes:
  postgres-data:
  mysql-data:
  mongo-data:
