services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invest_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - backend_default

networks:
  backend_default:
    external: true
